### ISSUE TITLE
Custom field data is not posted to paypal

### ISSUE THREAD

**Issue by abdulghaffar349** [Arsenal21/simple-wp-shopping-cart#5]
I have to pass some custom data to Paypal so I can get it back in the webhook. But there is not any custom data I'm getting from PayPal.I have seen in the plugin code that it fetches the IP and cart_id from the custom field and also plugin does not save my custom data in the database too. Any help will be appreciated. Thank you.

**Comment by Arsenal21** [comment]
PayPal has a limit on the number of characters that can be passed via the "custom" field. So it's generally not a good idea to try to pass too much data using that. 

This plugin triggers the following filter hook which you can use to add data to that "custom" field:
`
wpspc_cart_custom_field_value
`
A more workable solution is probably to use the following addon of the plugin where it saves the data with the cart order (so all the data doesn't need to be passed to PayPal since PayPal won't allow that):
https://www.tipsandtricks-hq.com/ecommerce/wp-simple-cart-collect-customer-input-in-the-shopping-cart-4396
